### ISSUE TITLE
HI,Can you tell me how to use this?

### ISSUE THREAD

**Issue by shore-frank** [ferhatabd/MobilePlayer#1]

**Comment by ferhatabd** [comment]
Hi @shore-frank! 

I have created a simple [starter project](https://github.com/ferhatabd/MobilePlayerDev), please check it out and let me know how it goes :)
In the framework itself there is a lot that can be configured UI wise, for which it's the best to check the original repo docs 
[here](https://github.com/sahin/mobileplayer-ios)

Hope this helps
Ferhat
